from __future__ import annotations

import asyncio
import json
from pathlib import Path
from datetime import timedelta
from typing import Any

from dotenv import load_dotenv
from sqlalchemy import select

load_dotenv(Path(__file__).resolve().with_name(".env"), override=False)

from backend.core.config import DEFAULT_BOOKING_DAYS_AHEAD, DEFAULT_TIMEZONE_OFFSET_MINUTES
from backend.core.db import SessionLocal
from backend.models import CinemaSettings, Movie, Show
from backend.services.booking import cinema_now


def movie(
    *,
    title: str,
    genre: str,
    description: str,
    poster: str,
    gallery: list[str],
    trailer_id: str,
    duration: int,
    age: int,
    year: int,
    country: str,
    director: str,
    cast: list[str],
    imdb: float,
    kinopoisk: float,
    internal_rating: float,
    sort_order: int,
    sessions: list[str],
) -> dict[str, Any]:
    return {
        "title": title,
        "genre": genre,
        "description": description,
        "poster": poster,
        "gallery_json": json.dumps(gallery, ensure_ascii=False),
        "trailer_id": trailer_id,
        "duration": duration,
        "age": age,
        "year": year,
        "country": country,
        "director": director,
        "cast_json": json.dumps(cast, ensure_ascii=False),
        "imdb": imdb,
        "kinopoisk": kinopoisk,
        "internal_rating": internal_rating,
        "ticket_price": None,
        "is_published": True,
        "sort_order": sort_order,
        "times": list(sessions),
    }


DEMO_MOVIES: list[dict[str, Any]] = [
    movie(
        title="Интерстеллар",
        genre="Фантастика",
        description="Эпическое путешествие сквозь космос и время: группа исследователей ищет новый дом для человечества, пока на Земле заканчиваются ресурсы.",
        poster="https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg",
            "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
        ],
        trailer_id="zSWdZVtXT7E",
        duration=169,
        age=12,
        year=2014,
        country="США, Великобритания, Канада",
        director="Кристофер Нолан",
        cast=["Мэттью Макконахи", "Энн Хэтэуэй", "Джессика Честейн", "Майкл Кейн"],
        imdb=8.7,
        kinopoisk=8.6,
        internal_rating=9.1,
        sort_order=1,
        sessions=["10:30", "14:00", "18:30", "22:10"],
    ),
    movie(
        title="Марсианин",
        genre="Фантастика",
        description="Астронавт Марк Уотни остаётся один на Марсе и превращает борьбу за выживание в инженерный, остроумный и очень человеческий эксперимент.",
        poster="https://image.tmdb.org/t/p/w500/pjYWdykADVLTCh5g475RnI2hWIN.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/lzMS0CI3FLQYC5EgJoWeIaEt0lm.jpg",
            "https://image.tmdb.org/t/p/w500/pjYWdykADVLTCh5g475RnI2hWIN.jpg",
        ],
        trailer_id="ej3ioOneTy8",
        duration=144,
        age=12,
        year=2015,
        country="США, Великобритания",
        director="Ридли Скотт",
        cast=["Мэтт Дэймон", "Джессика Честейн", "Кристен Уиг", "Чиветел Эджиофор"],
        imdb=8.0,
        kinopoisk=7.8,
        internal_rating=8.7,
        sort_order=2,
        sessions=["11:00", "15:20", "19:20", "22:30"],
    ),
    movie(
        title="Бэтмен",
        genre="Боевик",
        description="Мрачный детектив о первых годах Брюса Уэйна в маске: Готэм погружается в страх, а Загадочник раскрывает гнилую сердцевину города.",
        poster="https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg",
            "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        ],
        trailer_id="mqqft2x_Aa4",
        duration=176,
        age=16,
        year=2022,
        country="США",
        director="Мэтт Ривз",
        cast=["Роберт Паттинсон", "Зои Кравиц", "Пол Дано", "Колин Фаррелл"],
        imdb=7.8,
        kinopoisk=7.9,
        internal_rating=8.5,
        sort_order=3,
        sessions=["12:20", "16:40", "20:40"],
    ),
    movie(
        title="Дюна",
        genre="Фантастика",
        description="Наследник великого дома оказывается в центре войны за пустынную планету Арракис, где решается будущее империи и рождается легенда.",
        poster="https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/qVgZu5BTx6pu4owCvVOm4zjTfOi.jpg",
            "https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg",
        ],
        trailer_id="n9xhJrPXop4",
        duration=155,
        age=12,
        year=2021,
        country="США, Канада",
        director="Дени Вильнёв",
        cast=["Тимоти Шаламе", "Ребекка Фергюсон", "Оскар Айзек", "Зендея"],
        imdb=8.0,
        kinopoisk=7.7,
        internal_rating=8.8,
        sort_order=4,
        sessions=["10:00", "13:50", "17:40", "21:30"],
    ),
    movie(
        title="Бегущий по лезвию 2049",
        genre="Фантастика",
        description="Офицер Кей раскрывает тайну, способную разрушить хрупкий порядок будущего, и отправляется искать легендарного Рика Декарда.",
        poster="https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg",
            "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        ],
        trailer_id="gCcx85zbxz4",
        duration=164,
        age=16,
        year=2017,
        country="США, Великобритания, Канада",
        director="Дени Вильнёв",
        cast=["Райан Гослинг", "Харрисон Форд", "Ана де Армас", "Сильвия Хукс"],
        imdb=8.0,
        kinopoisk=7.8,
        internal_rating=8.6,
        sort_order=5,
        sessions=["11:40", "16:00", "20:20"],
    ),
    movie(
        title="Человек-паук: Нет пути домой",
        genre="Фантастика",
        description="После раскрытия личности Питер Паркер просит помощи у Доктора Стрэнджа, но заклинание открывает двери в мультивселенную.",
        poster="https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/AeK2MPOpYrOOgZNfFnfwp0L8tNn.jpg",
            "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        ],
        trailer_id="JfVOs4VSpmA",
        duration=148,
        age=12,
        year=2021,
        country="США",
        director="Джон Уоттс",
        cast=["Том Холланд", "Зендея", "Бенедикт Камбербэтч", "Джейкоб Баталон"],
        imdb=8.2,
        kinopoisk=8.0,
        internal_rating=8.7,
        sort_order=6,
        sessions=["10:20", "14:10", "18:00", "21:50"],
    ),
    movie(
        title="Мстители: Финал",
        genre="Фантастика",
        description="Оставшиеся герои Marvel собираются для последней попытки вернуть исчезнувших и поставить точку в битве с Таносом.",
        poster="https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
            "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
        ],
        trailer_id="TcMBFSGVi1c",
        duration=181,
        age=12,
        year=2019,
        country="США",
        director="Энтони Руссо, Джо Руссо",
        cast=["Роберт Дауни-младший", "Крис Эванс", "Скарлетт Йоханссон", "Марк Руффало"],
        imdb=8.4,
        kinopoisk=7.7,
        internal_rating=8.8,
        sort_order=7,
        sessions=["12:00", "16:20", "20:40"],
    ),
    movie(
        title="Чужой",
        genre="Ужасы",
        description="Экипаж космического буксира получает сигнал бедствия и сталкивается с существом, превращающим замкнутый корабль в ловушку.",
        poster="https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
            "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
        ],
        trailer_id="jQ5lPt9edzQ",
        duration=117,
        age=18,
        year=1979,
        country="США, Великобритания",
        director="Ридли Скотт",
        cast=["Сигурни Уивер", "Том Скеррит", "Вероника Картрайт", "Яфет Котто"],
        imdb=8.5,
        kinopoisk=8.1,
        internal_rating=8.9,
        sort_order=8,
        sessions=["13:00", "17:10", "22:00"],
    ),
    movie(
        title="Гладиатор II",
        genre="Исторический боевик",
        description="Новая глава саги о Риме: взрослая легенда Колизея возвращает зрителя к интригам империи, арене и цене свободы.",
        poster="https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg",
            "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        ],
        trailer_id="4rgYUipGJNo",
        duration=148,
        age=18,
        year=2024,
        country="США, Великобритания",
        director="Ридли Скотт",
        cast=["Пол Мескал", "Педро Паскаль", "Дензел Вашингтон", "Конни Нильсен"],
        imdb=6.5,
        kinopoisk=6.8,
        internal_rating=8.1,
        sort_order=9,
        sessions=["11:30", "15:40", "19:50"],
    ),
    movie(
        title="Ford против Ferrari",
        genre="Драма",
        description="Инженер Кэрролл Шелби и гонщик Кен Майлз создают автомобиль, способный бросить вызов Ferrari в легендарной гонке Ле-Ман.",
        poster="https://image.tmdb.org/t/p/w500/dR1Ju50iudrOh3YgfwkAU1g2HZe.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/2vq5GTJOahE03mNYZGxIynlHcWr.jpg",
            "https://image.tmdb.org/t/p/w500/dR1Ju50iudrOh3YgfwkAU1g2HZe.jpg",
        ],
        trailer_id="I3h9Z89U9ZA",
        duration=152,
        age=12,
        year=2019,
        country="США",
        director="Джеймс Мэнголд",
        cast=["Кристиан Бэйл", "Мэтт Дэймон", "Джон Бернтал", "Катрина Балф"],
        imdb=8.1,
        kinopoisk=8.2,
        internal_rating=8.7,
        sort_order=10,
        sessions=["10:50", "14:50", "18:50", "22:20"],
    ),
    movie(
        title="Оппенгеймер",
        genre="Драма",
        description="История физика Роберта Оппенгеймера и проекта, изменившего ход XX века: научный триумф, моральная цена и политическое давление.",
        poster="https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg",
            "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        ],
        trailer_id="uYPbbksJxIg",
        duration=180,
        age=18,
        year=2023,
        country="США, Великобритания",
        director="Кристофер Нолан",
        cast=["Киллиан Мёрфи", "Эмили Блант", "Мэтт Дэймон", "Роберт Дауни-младший"],
        imdb=8.3,
        kinopoisk=8.2,
        internal_rating=8.9,
        sort_order=11,
        sessions=["12:40", "17:00", "21:20"],
    ),
    movie(
        title="Начало",
        genre="Фантастика",
        description="Профессиональный похититель идей получает шанс на искупление: вместо кражи он должен внедрить мысль в глубины чужого сна.",
        poster="https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
            "https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        ],
        trailer_id="YoHD9XEInc0",
        duration=148,
        age=12,
        year=2010,
        country="США, Великобритания",
        director="Кристофер Нолан",
        cast=["Леонардо ДиКаприо", "Джозеф Гордон-Левитт", "Эллиот Пейдж", "Том Харди"],
        imdb=8.8,
        kinopoisk=8.7,
        internal_rating=9.2,
        sort_order=12,
        sessions=["10:10", "14:00", "18:10", "22:00"],
    ),
    movie(
        title="Тёмный рыцарь",
        genre="Боевик",
        description="Бэтмен, Гордон и Харви Дент пытаются остановить Джокера, который превращает Готэм в испытание для морали и порядка.",
        poster="https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
            "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        ],
        trailer_id="EXeTwQWrcwY",
        duration=152,
        age=16,
        year=2008,
        country="США, Великобритания",
        director="Кристофер Нолан",
        cast=["Кристиан Бэйл", "Хит Леджер", "Аарон Экхарт", "Майкл Кейн"],
        imdb=9.0,
        kinopoisk=8.5,
        internal_rating=9.3,
        sort_order=13,
        sessions=["11:20", "15:30", "19:40"],
    ),
    movie(
        title="Аватар",
        genre="Фантастика",
        description="На Пандоре бывший морпех оказывается между военной миссией и новым миром, где природа, культура и любовь меняют его выбор.",
        poster="https://image.tmdb.org/t/p/w500/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
            "https://image.tmdb.org/t/p/w500/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
        ],
        trailer_id="5PSNL1qE6VY",
        duration=162,
        age=12,
        year=2009,
        country="США",
        director="Джеймс Кэмерон",
        cast=["Сэм Уортингтон", "Зои Салдана", "Сигурни Уивер", "Стивен Лэнг"],
        imdb=7.9,
        kinopoisk=7.9,
        internal_rating=8.5,
        sort_order=14,
        sessions=["12:10", "16:30", "20:50"],
    ),
    movie(
        title="Топ Ган: Мэверик",
        genre="Боевик",
        description="Легендарный пилот возвращается инструктором, чтобы подготовить новую команду к почти невозможной миссии.",
        poster="https://image.tmdb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
            "https://image.tmdb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
        ],
        trailer_id="qSqVVswa420",
        duration=131,
        age=12,
        year=2022,
        country="США",
        director="Джозеф Косински",
        cast=["Том Круз", "Майлз Теллер", "Дженнифер Коннелли", "Глен Пауэлл"],
        imdb=8.2,
        kinopoisk=8.0,
        internal_rating=8.8,
        sort_order=15,
        sessions=["10:40", "14:20", "18:00", "21:40"],
    ),
    movie(
        title="Джокер",
        genre="Драма",
        description="Одинокий комик Артур Флек постепенно превращает личную боль и унижение в символ хаоса для всего Готэма.",
        poster="https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/rlay2M5QYvi6igbGcFjq8jxeusY.jpg",
            "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        ],
        trailer_id="zAGVQLHvwOY",
        duration=122,
        age=18,
        year=2019,
        country="США, Канада",
        director="Тодд Филлипс",
        cast=["Хоакин Феникс", "Роберт Де Ниро", "Зази Битц", "Фрэнсис Конрой"],
        imdb=8.4,
        kinopoisk=8.0,
        internal_rating=8.6,
        sort_order=16,
        sessions=["13:30", "17:30", "21:30"],
    ),
    movie(
        title="Безумный Макс: Дорога ярости",
        genre="Боевик",
        description="Постапокалиптическая погоня через пустыню, где Фуриоса и Макс бросают вызов тирании Несмертного Джо.",
        poster="https://image.tmdb.org/t/p/w500/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/uT895WNwm0aIJRtGizcQhrejWUo.jpg",
            "https://image.tmdb.org/t/p/w500/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg",
        ],
        trailer_id="hEJnMQG9ev8",
        duration=120,
        age=16,
        year=2015,
        country="Австралия, США",
        director="Джордж Миллер",
        cast=["Том Харди", "Шарлиз Терон", "Николас Холт", "Хью Кияс-Бёрн"],
        imdb=8.1,
        kinopoisk=7.8,
        internal_rating=8.7,
        sort_order=17,
        sessions=["11:10", "15:00", "18:50", "22:40"],
    ),
    movie(
        title="Матрица",
        genre="Фантастика",
        description="Хакер Нео узнаёт, что привычная реальность — симуляция, и вступает в борьбу за пробуждение человечества.",
        poster="https://image.tmdb.org/t/p/w500/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg",
            "https://image.tmdb.org/t/p/w500/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
        ],
        trailer_id="vKQi3bBA1y8",
        duration=136,
        age=16,
        year=1999,
        country="США, Австралия",
        director="Лана Вачовски, Лилли Вачовски",
        cast=["Киану Ривз", "Лоренс Фишбёрн", "Кэрри-Энн Мосс", "Хьюго Уивинг"],
        imdb=8.7,
        kinopoisk=8.5,
        internal_rating=9.0,
        sort_order=18,
        sessions=["12:30", "16:20", "20:10"],
    ),
    movie(
        title="Стражи Галактики. Часть 3",
        genre="Фантастика",
        description="Последняя большая миссия команды Стражей: спасение Ракеты раскрывает прошлое героя и проверяет семью на прочность.",
        poster="https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
            "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
        ],
        trailer_id="u3V5KDHRQvk",
        duration=150,
        age=12,
        year=2023,
        country="США",
        director="Джеймс Ганн",
        cast=["Крис Пратт", "Зои Салдана", "Дэйв Батиста", "Карен Гиллан"],
        imdb=7.9,
        kinopoisk=8.0,
        internal_rating=8.5,
        sort_order=19,
        sessions=["10:15", "14:10", "18:05", "22:00"],
    ),
    movie(
        title="Довод",
        genre="Фантастика",
        description="Агент получает миссию, где время движется не только вперёд: инверсия становится оружием в борьбе за будущее мира.",
        poster="https://image.tmdb.org/t/p/w500/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/mQOUyqDybTqxl73hO5LujCZsM1o.jpg",
            "https://image.tmdb.org/t/p/w500/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
        ],
        trailer_id="LdOM0x0XDMo",
        duration=150,
        age=16,
        year=2020,
        country="США, Великобритания",
        director="Кристофер Нолан",
        cast=["Джон Дэвид Вашингтон", "Роберт Паттинсон", "Элизабет Дебики", "Кеннет Брана"],
        imdb=7.3,
        kinopoisk=7.5,
        internal_rating=8.1,
        sort_order=20,
        sessions=["13:10", "17:20", "21:30"],
    ),
    movie(
        title="Одержимость",
        genre="Драма",
        description="Молодой барабанщик попадает под жёсткое наставничество дирижёра, для которого величие важнее комфорта и правил.",
        poster="https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg",
            "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        ],
        trailer_id="7d_jQycdQGo",
        duration=107,
        age=16,
        year=2014,
        country="США",
        director="Дэмьен Шазелл",
        cast=["Майлз Теллер", "Дж. К. Симмонс", "Пол Райзер", "Мелисса Бенойст"],
        imdb=8.5,
        kinopoisk=8.4,
        internal_rating=9.0,
        sort_order=21,
        sessions=["12:00", "16:00", "20:00"],
    ),
    movie(
        title="Всё везде и сразу",
        genre="Фантастика",
        description="Обычная владелица прачечной внезапно оказывается ключом к спасению мультивселенной — через хаос, семью и принятие себя.",
        poster="https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
        gallery=[
            "https://image.tmdb.org/t/p/w1280/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg",
            "https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
        ],
        trailer_id="wxN1T1uxQ2g",
        duration=140,
        age=16,
        year=2022,
        country="США",
        director="Дэн Кван, Дэниел Шайнерт",
        cast=["Мишель Йео", "Ке Хюи Куан", "Стефани Сюй", "Джейми Ли Кёртис"],
        imdb=7.8,
        kinopoisk=7.2,
        internal_rating=8.4,
        sort_order=22,
        sessions=["11:50", "15:50", "19:50"],
    ),
]


async def seed_demo_movies() -> None:
    created = 0
    skipped = 0
    # The window follows the cinema's calendar, like every other date in the app.
    first_day = cinema_now(DEFAULT_TIMEZONE_OFFSET_MINUTES).date()
    window = [
        (first_day + timedelta(days=offset)).isoformat()
        for offset in range(DEFAULT_BOOKING_DAYS_AHEAD)
    ]
    async with SessionLocal() as session:
        if await session.get(CinemaSettings, 1) is None:
            session.add(CinemaSettings(id=1))
        for payload in DEMO_MOVIES:
            values = dict(payload)
            times = values.pop("times", [])
            exists = await session.scalar(
                select(Movie.id).where(Movie.title == values["title"]).limit(1)
            )
            if exists is not None:
                skipped += 1
                continue
            item = Movie(**values)
            session.add(item)
            await session.flush()
            session.add_all(
                Show(movie_id=item.id, show_date=show_date, start_time=start_time)
                for show_date in window
                for start_time in times
            )
            created += 1
        await session.commit()
    print(f"Demo movie seed complete: created={created}, skipped_existing={skipped}")


if __name__ == "__main__":
    asyncio.run(seed_demo_movies())
