import type { MovieDetail, MoviePayload } from '../../api'

/** Shared by the catalog editor and the new-release manager, which both PATCH movies. */
export const toMoviePayload = (movie: MovieDetail): MoviePayload => ({
  title: movie.title,
  genre: movie.genre,
  description: movie.description,
  poster: movie.poster,
  trailer_id: movie.trailer_id,
  duration: movie.duration,
  age: movie.age,
  year: movie.year,
  country: movie.country,
  director: movie.director,
  cast: movie.cast,
  gallery: movie.gallery,
  imdb: movie.imdb,
  kinopoisk: movie.kinopoisk,
  internal_rating: movie.internal_rating,
  ticket_price: movie.ticket_price,
  is_published: movie.is_published,
  is_new: movie.is_new,
  new_until: movie.new_until,
  is_hit: movie.is_hit,
  sort_order: movie.sort_order,
})

export const emptyMoviePayload = (): MoviePayload => ({
  title: '',
  genre: '',
  description: '',
  poster: '',
  trailer_id: '',
  duration: 90,
  age: 12,
  year: new Date().getFullYear(),
  country: '',
  director: '',
  cast: [],
  gallery: [],
  imdb: 0,
  kinopoisk: 0,
  internal_rating: null,
  ticket_price: null,
  is_published: true,
  is_new: false,
  new_until: '',
  is_hit: false,
  sort_order: 0,
})
